services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins
    user: root
    ports:
      - "8082:8080"   # Jenkins UI
      - "50000:50000" # Agent
    volumes:
      - jenkins_home:/var/jenkins_home
      - ${HOME}/.m2:/var/jenkins_home/.m2               # Maven caching
      - /var/run/docker.sock:/var/run/docker.sock       # Access Docker engine
      - ${HOME}/.docker:/root/.docker                   # Docker credentials
      - ${HOME}/.kube:/root/.kube                       # Kube config for minikube access
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false

volumes:
  jenkins_home:
