services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins
    user: root
    ports:
      - "8082:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - ${HOME}/.m2:/var/jenkins_home/.m2
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/.docker:/root/.docker
      - ${HOME}/.kube:/root/.kube
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false

volumes:
  jenkins_home:
