apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
data:
  logstash.conf: |
    input {
      tcp {
        port => 5044
        codec => json_lines
      }
    }
    output {
      elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "task-management-logs-%{+YYYY.MM.dd}"
      }
    
      stdout { codec => rubydebug }
    }
