server:
  port: 8080

spring:
  application:
    name: task-management
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://<mac_ip>:3306/task_db}
    username: taskuser
    password: taskpass
    driver: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  kafka:
    bootstrap-servers: kafka-service:9092
    properties:
      schema.registry.url: http://schema-registry:8081
    consumer:
      group-id: task-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        schema.registry.url: http://schema-registry:8081
        specific.avro.reader: true
  redis:
    host: localhost
    port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-app-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8

shedlock:
  redis:
    key-prefix: shedlock

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,beans,env,loggers,prometheus
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: task-management

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: method
    display-request-duration: true
    group-order: DESC
  show-actuator: true

api:
  version: 1.0.0

scheduler:
  cron: "0 0 * * * *"

jwt:
  secret: averysecuresecretkeyformyjwtapp1234567890
  expiration: 36000000  # 10 hours in ms
