server:
  port: 8080

spring:
  application:
    name: task-management
  datasource:
    url: jdbc:mysql://localhost:3306/task_db
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      schema.registry.url: http://localhost:8081
    consumer:
      group-id: task-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        schema.registry.url: http://localhost:8081
        specific.avro.reader: true
  redis:
    host: localhost
    port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-app-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8

shedlock:
  redis:
    key-prefix: shedlock

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,beans,env,loggers
  endpoint:
    health:
      show-details: always  # Show full health details

scheduler:
  cron: "0 0 * * * *"

jwt:
  secret: averysecuresecretkeyformyjwtapp1234567890
  expiration: 36000000  # 10 hours in ms