apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-management-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-management
  template:
    metadata:
      labels:
        app: task-management
    spec:
      containers:
        - name: task-management
          image: dishantkkk/task-management:latest
          ports:
            - containerPort: 8080
